# -*- coding: utf-8 -*-

"""
multiauthsample

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import unittest
from tests.http_response_catcher import HttpResponseCatcher
from multiauthsample.configuration import Configuration
from multiauthsample.multiauthsample_client import MultiauthsampleClient
from multiauthsample.http.auth.o_auth_bearer_token import OAuthBearerTokenCredentials


class ControllerTestBase(unittest.TestCase):

    """All test classes inherit from this base class. It abstracts out
    common functionality and configuration variables set up."""

    client = None
    config = None

    @classmethod
    def setUpClass(cls):
        """Class method called once before running tests in a test class."""
        cls.request_timeout = 30
        cls.assert_precision = 0.01
        cls.config = ControllerTestBase.create_configuration()
        cls.client = MultiauthsampleClient(config=cls.config)

        o_auth_ccg_token = cls.client.o_auth_ccg.fetch_token()
        o_auth_ccg_credentials = cls.config.o_auth_ccg_credentials\
            .clone_with(o_auth_token=o_auth_ccg_token)
        cls.config = cls.config.clone_with(o_auth_ccg_credentials=o_auth_ccg_credentials)

        o_auth_acg_token = cls.client.o_auth_acg.fetch_token('910b000d4f')
        o_auth_acg_credentials = cls.config.o_auth_acg_credentials\
            .clone_with(o_auth_token=o_auth_acg_token)
        cls.config = cls.config.clone_with(o_auth_acg_credentials=o_auth_acg_credentials)

        o_auth_ropcg_token = cls.client.o_auth_ropcg.fetch_token()
        o_auth_ropcg_credentials = cls.config.o_auth_ropcg_credentials\
            .clone_with(o_auth_token=o_auth_ropcg_token)
        cls.config = cls.config.clone_with(o_auth_ropcg_credentials=o_auth_ropcg_credentials)

        cls.client = MultiauthsampleClient(config=cls.config)

    @staticmethod
    def create_configuration():
        return Configuration(
            o_auth_bearer_token_credentials=OAuthBearerTokenCredentials(
                access_token='azHmdOe09EdchxeWsdnplkQbv76sJH'),
            access_token='azHmdOe09EdchxeWsdnplkQbv76sJH',
            http_call_back=HttpResponseCatcher())
